/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:a523f427-7afb-4d24-b928-1e2db993d2c9",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_xzPm44j8p",
    "aws_user_pools_web_client_id": "6bc6nuqu1q81bno974c8but0cg",
    "oauth": {}
};


export default awsmobile;
