/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:67c2c244-6c4b-4913-9ea6-45c898bdf654",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_yQ8fssF4Z",
    "aws_user_pools_web_client_id": "75gmj0quqk19on3sm5p5rh8mb2",
    "oauth": {} 
};


export default awsmobile;
